---
title: "Dissertation Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(dplyr)
library(DT)
library(flexdashboard)
library(ggplot2)
library(lubridate)
library(timevis)
```

```{r parse data, include=FALSE}
raw_text <- readLines(file.path("..", "ProjectNotes.md"))

# Create a blank dataframe, which we'll fill in below:
parsed_data <- data.frame(
  group=character(),
  content=character(), 
  start=character(), 
  end=character(),
  style=character(),
  start_represents_deadline=logical(),
  stringsAsFactors=FALSE
)

# Loop though the todo file's lines, and find and parse the todo lines within it:
# See the ?timevis documentation to understand the column names and
# values that are used below:
for (line in raw_text) {
  line_data <- data.frame(
    group=character(),
    content=character(), 
    start=character(), 
    end=character(),
    style=character(),
    start_represents_deadline=logical(),
    stringsAsFactors=FALSE
  )
  
  status_marker_regex <- "\\s*- \\[(.)\\].*"
  status_marker <- gsub(status_marker_regex, "\\1", line, perl = TRUE)
  
  # If no match was found above, status_marker will be the same as line. In that case, we
  # can consider this not to be a todo line:
  if (status_marker == line) {
    next 
  }
  
  if (status_marker == " ") {
    line_data[1, "group"] <- "TODO" 
  } else if (status_marker == "/") {
    line_data[1, "group"] <- "RIGHT NOW" 
  } else if (status_marker == "x" || status_marker == "X") {
    line_data[1, "group"] <- "DONE" 
  } else if (status_marker == "V" || status_marker == "v") {
    line_data[1, "group"] <- "DONE" 
  } else if (status_marker == ">") {
    line_data[1, "group"] <- "SCHEDULED" 
  } else if (status_marker == "<") {
    line_data[1, "group"] <- "MIGRATED" 
  } else if (status_marker == "-") {
    line_data[1, "group"] <- "CANCELLED" 
  } else if (status_marker == "O") {
    line_data[1, "group"] <- "BLOCKED" 
  }
    
  description <- gsub(
    paste0(status_marker_regex, "? (.*?)(\\s*(SCHEDULED|DEADLINE).*|$)"),
    "\\2", 
    line, 
    perl = TRUE
  )
  
  if (description != line) {
    line_data[1, "content"] <- description
  }
  
  scheduled <- gsub(".* SCHEDULED: (.*?)(\\s|$).*", "\\1", line, perl = TRUE)
  if (scheduled != line) {
    line_data[1, "start"] <- scheduled
  }
  
  deadline <- gsub(".* DEADLINE: (.*?)(\\s|$).*", "\\1", line, perl = TRUE)
  if (deadline != line) {
    line_data[1, "end"] <- deadline
  }
  
  # These colors are colorblind safe, per https://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=3:
  scheduled_color <- "#91bfdb"
  deadline_color <- "#fc8d59"
  
  if (!is.na(line_data[1, "start"]) && is.na(line_data[1, "end"])) {
    line_data[1, "style"] <- paste0("color: black; background: white; border-bottom: .5em solid ", scheduled_color)
  } else if (is.na(line_data[1, "start"]) && !is.na(line_data[1, "end"])) {
    # timevis requires every charted line to have a 'start' value. In this
    # case, we will call the Deadline date the "start", but will mark it with a different
    # color:
    line_data[1, "start"] <- line_data[1, "end"]
    line_data[1, "end"] <- NA
    line_data[1, "style"] <- paste0("color: black; background: white; border: 1px solid ", deadline_color, "; border-bottom: .5em solid ", deadline_color, ";")
    line_data[1, "start_represents_deadline"] <- TRUE
  } else {
    # If both start and end are set:
    line_data[1, "style"] <- paste0("color: black; background: white; border-image-source: linear-gradient(to right, ", scheduled_color,", ", deadline_color, "); border-image-slice: 1; border-bottom: .5em solid; border-top: 1px solid; border-left: 1px solid; border-right: 1px solid;")
  }
  
  parsed_data <- rbind(parsed_data, line_data)
}
```

Column {data-width=650}
-----------------------------------------------------------------------

### Gantt Chart

```{r}
parsed_data %>% 
  filter(
    !is.na(start)
  ) %>% 
  timevis(
    groups = tribble(
      ~id,          ~content,     ~style,
      "TODO",       "TODO",       "color: #FF0000", 
      "RIGHT NOW",  "RIGHT NOW",  "color: #0000FF",
      "SCHEDULED",  "SCHEDULED",  "color: #0000FF",
      "MIGRATED",   "MIGRATED",   "color: #9370D8",
      "BLOCKED",    "BLOCKED",    "color: #FFA500",
      "CANCELLED",  "CANCELLED",  "color: #82d882",
      "DONE",       "DONE",       "color: #90EE90",
    )
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Status Breakdown

```{r}
ggplot(parsed_data, aes(
  factor(group, levels = c(
    "TODO",
    "RIGHT NOW",
    "SCHEDULED",
    "MIGRATED",
    "CANCELLED",
    "BLOCKED",
    "DONE"
  )), 
  fill = factor(group)
)) + 
  xlab("Status") + 
  ylab("Count") +
  geom_bar() + 
  theme_classic() +
  scale_fill_manual(values = c(
    "TODO" = "#FF0000", 
    "RIGHT NOW" = "#0000FF",
    "SCHEDULED" = "#0000FF",
    "MIGRATED" = "#9370D8",
    "CANCELLED" = "#82d882",
    "BLOCKED" = "#FFA500",
    "DONE" = "#90EE90"
  )) + 
   theme(
     legend.position = "none",
     text = element_text(size=20),
     axis.text.x = element_text(angle = 30, vjust = 0.5)
   )
```

### Scheduled to start two weeks from now or earlier

```{r}
datatable(
  parsed_data %>% 
    filter(
      # + 14 adds 14 days
      ymd(start) <= (Sys.Date() + 14) & 
      group != "DONE"
    ) %>% 
    select(-style, -start_represents_deadline) %>% 
    rename(
      Status = group,
      Description = content,
      Scheduled = start,
      Deadline = end
    ),
  options = list(pageLength = 5)
)
```

### Deadline in the next week, and Overdue

```{r}
datatable(
  parsed_data %>% 
    filter(
      start_represents_deadline == TRUE &
      ymd(start) <= (Sys.Date() + 7) & 
      group != "DONE"
    ) %>% 
    select(-style, -start_represents_deadline) %>% 
    rename(
      Status = group,
      Description = content,
      Scheduled = start,
      Deadline = end
    ),
  options = list(pageLength = 5)
)
```

### Non-scheduled tasks


```{r}
datatable(
  parsed_data %>% 
    filter(
      is.na(start) &
      is.na(end) &
      group != "DONE"
    ) %>% 
    select(-style, -start_represents_deadline) %>% 
    rename(
      Status = group,
      Description = content,
      Scheduled = start,
      Deadline = end
    ),
  options = list(pageLength = 5)
)
```